# Generated by Django 4.2.5 on 2023-09-17 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='disc',
            new_name='disc1',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='img',
            new_name='img1',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='name1',
        ),
    ]
