# Generated by Django 4.2.5 on 2023-09-17 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_rename_disc_team_disc1_rename_img_team_img1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='disc1',
            new_name='disc',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='img1',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name1',
            new_name='name',
        ),
    ]
